---
- name: install bind packages
  apt: pkg={{ item }} state={{ bind_pkg_state }}
  with_items: "{{ bind_pkgs }}"

- name: setup zone directories
  file: dest={{ bind_base_zones_path }}/{{ item }} state=directory owner={{ bind_user }} group={{ bind_group }} mode=0755
  with_items:
  - masters
  - slaves

- name: set reverse date
  set_fact:
    bind_reverse_date: "{{ lookup('pipe','date +%s') }}"
  
- name: print reverse date
  debug:
    msg: "{{ bind_reverse_date }}"

- name: copy db.root file
  copy:
    src: db.root
    dest: "{{ bind_config_basepath }}/db.root"
    force: no

- name: setup zones
  template: src=named.conf.local.{{ item }}.j2 dest={{ bind_config_basepath }}/named.conf.local.{{ item }} owner={{ bind_user }} group={{ bind_group }} mode=0600
  with_items:
    - master
    - slave
    - forward
  notify: reload bind

- name: setup zones files for named zones
  template: src=zones.j2 dest={{ bind_config_basepath }}/db.{{ item.name }} owner={{ bind_user }} group={{ bind_group }} mode=0600
  with_items:
    - "{{ bind_config_master_zones }}"

- name: configure bind
  copy: src=named.conf dest={{ bind_config_basepath }}/named.conf owner={{ bind_user }} group={{ bind_group }} mode=0600
  notify: restart bind

- name: configure bind options
  template: src=named.conf.options.j2 dest={{ bind_config_basepath }}/named.conf.options owner={{ bind_user }} group={{ bind_group }} mode=0600
  notify: restart bind

#- name: Copy master zone files
#  copy: src={{ bind_masterzones_path }}/db.{{ item.name }} dest={{ bind_base_zones_path }}/{{bind_masterzones_path}} owner={{ bind_user }} group={{ bind_group }}
#  with_items: "{{ bind_config_master_zones }}"
#  notify: reload bind
#  tags: bind-zones

- name: start/stop bind service
  service: name={{ bind_service_name }} state={{ bind_service_state }} enabled={{ bind_service_enabled }}
